### ISSUE TITLE
Add hardening modules

### ISSUE THREAD

**Issue by vladgh** [vghn/puppet#28]
https://github.com/dev-sec/hardening/tree/master/puppet

However, `saz/ssh` is a dependency and it needs to replace `ghoneycutt/ssh`

**Comment by vladgh** [comment]
Replace `ssh::keys` with `profile::base::ssh_authorized_keys` and add the following options for the saz/ssh module:

``` YAML
ssh::server_options:
  PermitRootLogin: 'no'
  PasswordAuthentication: 'no'
```
